### ISSUE TITLE
“origin” is not special

### ISSUE THREAD

**Issue by michaelvarhol** [pavolnoga1/pnks#10]
“origin” is not specialJust like the branch name “master” does not have any special meaning in Git, neither does “origin”. While “master” is the default name for a starting branch when you run git init which is the only reason it’s widely used, “origin” is the default name for a remote when you run git clone. If you run git clone -o booyah instead, then you will have booyah/master as your default remote branch.

**Comment by pavolnoga1** [comment]
I am not responsible for booyah branch (Typical AO excuse)
